document.write("aula 01 - exercicio 6")
var quantidade = parseFloat(prompt("digite a quantidade do produto"))
var preco = parseFloat(prompt("digite o preço do produto"))
var subtotal = (quantidade * preco)
document.write("o subtotal é" + subtotal +"<br>" )
var desconto = (subtotal * 0.10)
document.write("o desconto é" + desconto +"<br>")
var total = ( subtotal - desconto)
document.write("o valor final é" + total +"<br>" )